import abc
from kafka.metrics.stat import AbstractStat as AbstractStat
from typing import Any

class AbstractCompoundStat(AbstractStat, metaclass=abc.ABCMeta):
    __metaclass__: Any = ...
    def stats(self) -> None: ...

class NamedMeasurable:
    def __init__(self, metric_name: Any, measurable_stat: Any) -> None: ...
    @property
    def name(self): ...
    @property
    def stat(self): ...
