from typing import Any, Optional

class KafkaMetric:
    def __init__(self, metric_name: Any, measurable: Any, config: Any) -> None: ...
    @property
    def metric_name(self): ...
    @property
    def measurable(self): ...
    @property
    def config(self): ...
    @config.setter
    def config(self, config: Any) -> None: ...
    def value(self, time_ms: Optional[Any] = ...): ...
