import abc
from typing import Any

class AbstractMetricsReporter(metaclass=abc.ABCMeta):
    __metaclass__: Any = ...
    @abc.abstractmethod
    def init(self, metrics: Any) -> Any: ...
    @abc.abstractmethod
    def metric_change(self, metric: Any) -> Any: ...
    @abc.abstractmethod
    def metric_removal(self, metric: Any) -> Any: ...
    @abc.abstractmethod
    def configure(self, configs: Any) -> Any: ...
    @abc.abstractmethod
    def close(self) -> Any: ...
