from typing import Any, Optional

class MetricConfig:
    quota: Any = ...
    event_window: Any = ...
    time_window_ms: Any = ...
    tags: Any = ...
    def __init__(self, quota: Optional[Any] = ..., samples: int = ..., event_window: Any = ..., time_window_ms: Any = ..., tags: Optional[Any] = ...) -> None: ...
    @property
    def samples(self): ...
    @samples.setter
    def samples(self, value: Any) -> None: ...
