from typing import Any

class Quota:
    def __init__(self, bound: Any, is_upper: Any) -> None: ...
    @staticmethod
    def upper_bound(upper_bound: Any): ...
    @staticmethod
    def lower_bound(lower_bound: Any): ...
    def is_upper_bound(self): ...
    @property
    def bound(self): ...
    def is_acceptable(self, value: Any): ...
    def __hash__(self) -> Any: ...
    def __eq__(self, other: Any) -> Any: ...
    def __ne__(self, other: Any) -> Any: ...
