from typing import Any, Optional

PYPY: Any

def has_gzip(): ...
def has_snappy(): ...
def has_lz4(): ...
def gzip_encode(payload: Any, compresslevel: Optional[Any] = ...): ...
def gzip_decode(payload: Any): ...
def snappy_encode(payload: Any, xerial_compatible: bool = ..., xerial_blocksize: Any = ...): ...
def snappy_decode(payload: Any): ...

lz4_encode: Any

def lz4f_decode(payload: Any): ...

lz4_decode: Any
lz4_decode = lz4f_decode

def lz4_encode_old_kafka(payload: Any): ...
def lz4_decode_old_kafka(payload: Any): ...
