from typing import Any

log: Any

class Future:
    error_on_callbacks: bool = ...
    is_done: bool = ...
    value: Any = ...
    exception: Any = ...
    def __init__(self) -> None: ...
    def succeeded(self): ...
    def failed(self): ...
    def retriable(self): ...
    def success(self, value: Any): ...
    def failure(self, e: Any): ...
    def add_callback(self, f: Any, *args: Any, **kwargs: Any): ...
    def add_errback(self, f: Any, *args: Any, **kwargs: Any): ...
    def add_both(self, f: Any, *args: Any, **kwargs: Any): ...
    def chain(self, future: Any): ...
