from typing import Any

def xor_bytes(left: Any, right: Any): ...

class ScramClient:
    MECHANISMS: Any = ...
    nonce: Any = ...
    auth_message: str = ...
    salted_password: Any = ...
    user: Any = ...
    password: Any = ...
    hashfunc: Any = ...
    hashname: Any = ...
    stored_key: Any = ...
    client_key: Any = ...
    client_signature: Any = ...
    client_proof: Any = ...
    server_key: Any = ...
    server_signature: Any = ...
    def __init__(self, user: Any, password: Any, mechanism: Any) -> None: ...
    def first_message(self): ...
    def process_server_first_message(self, server_first_message: Any) -> None: ...
    def hmac(self, key: Any, msg: Any): ...
    def create_salted_password(self, salt: Any, iterations: Any) -> None: ...
    def final_message(self): ...
    def process_server_final_message(self, server_final_message: Any) -> None: ...
