from kafka.vendor.enum34 import IntEnum as IntEnum
from typing import Any, Optional

class ConfigResourceType(IntEnum):
    BROKER: Any = ...
    TOPIC: int = ...

class ConfigResource:
    resource_type: Any = ...
    name: Any = ...
    configs: Any = ...
    def __init__(self, resource_type: Any, name: Any, configs: Optional[Any] = ...) -> None: ...
