from typing import Any, Optional

class NewPartitions:
    total_count: Any = ...
    new_assignments: Any = ...
    def __init__(self, total_count: Any, new_assignments: Optional[Any] = ...) -> None: ...
