from kafka.errors import IllegalArgumentError as IllegalArgumentError
from typing import Any, Optional

class NewTopic:
    name: Any = ...
    num_partitions: Any = ...
    replication_factor: Any = ...
    replica_assignments: Any = ...
    topic_configs: Any = ...
    def __init__(self, name: Any, num_partitions: Any, replication_factor: Any, replica_assignments: Optional[Any] = ..., topic_configs: Optional[Any] = ...) -> None: ...
