from typing import Any

def encode_varint(value: Any, write: Any): ...
def size_of_varint(value: Any): ...
def decode_varint(buffer: Any, pos: int = ...): ...
def calc_crc32c(memview: Any, _crc32c: Any = ...): ...
def calc_crc32(memview: Any): ...
