from kafka.protocol.api import Request as Request, Response as Response
from kafka.protocol.types import Array as Array, Boolean as Boolean, Bytes as Bytes, Int16 as Int16, Int32 as Int32, Int64 as Int64, Int8 as Int8, Schema as Schema, String as String
from typing import Any

class ApiVersionResponse_v0(Response):
    API_KEY: int = ...
    API_VERSION: int = ...
    SCHEMA: Any = ...

class ApiVersionResponse_v1(Response):
    API_KEY: int = ...
    API_VERSION: int = ...
    SCHEMA: Any = ...

class ApiVersionResponse_v2(Response):
    API_KEY: int = ...
    API_VERSION: int = ...
    SCHEMA: Any = ...

class ApiVersionRequest_v0(Request):
    API_KEY: int = ...
    API_VERSION: int = ...
    RESPONSE_TYPE: Any = ...
    SCHEMA: Any = ...

class ApiVersionRequest_v1(Request):
    API_KEY: int = ...
    API_VERSION: int = ...
    RESPONSE_TYPE: Any = ...
    SCHEMA: Any = ...

class ApiVersionRequest_v2(Request):
    API_KEY: int = ...
    API_VERSION: int = ...
    RESPONSE_TYPE: Any = ...
    SCHEMA: Any = ...

ApiVersionRequest: Any
ApiVersionResponse: Any

class CreateTopicsResponse_v0(Response):
    API_KEY: int = ...
    API_VERSION: int = ...
    SCHEMA: Any = ...

class CreateTopicsResponse_v1(Response):
    API_KEY: int = ...
    API_VERSION: int = ...
    SCHEMA: Any = ...

class CreateTopicsResponse_v2(Response):
    API_KEY: int = ...
    API_VERSION: int = ...
    SCHEMA: Any = ...

class CreateTopicsResponse_v3(Response):
    API_KEY: int = ...
    API_VERSION: int = ...
    SCHEMA: Any = ...

class CreateTopicsRequest_v0(Request):
    API_KEY: int = ...
    API_VERSION: int = ...
    RESPONSE_TYPE: Any = ...
    SCHEMA: Any = ...

class CreateTopicsRequest_v1(Request):
    API_KEY: int = ...
    API_VERSION: int = ...
    RESPONSE_TYPE: Any = ...
    SCHEMA: Any = ...

class CreateTopicsRequest_v2(Request):
    API_KEY: int = ...
    API_VERSION: int = ...
    RESPONSE_TYPE: Any = ...
    SCHEMA: Any = ...

class CreateTopicsRequest_v3(Request):
    API_KEY: int = ...
    API_VERSION: int = ...
    RESPONSE_TYPE: Any = ...
    SCHEMA: Any = ...

CreateTopicsRequest: Any
CreateTopicsResponse: Any

class DeleteTopicsResponse_v0(Response):
    API_KEY: int = ...
    API_VERSION: int = ...
    SCHEMA: Any = ...

class DeleteTopicsResponse_v1(Response):
    API_KEY: int = ...
    API_VERSION: int = ...
    SCHEMA: Any = ...

class DeleteTopicsResponse_v2(Response):
    API_KEY: int = ...
    API_VERSION: int = ...
    SCHEMA: Any = ...

class DeleteTopicsResponse_v3(Response):
    API_KEY: int = ...
    API_VERSION: int = ...
    SCHEMA: Any = ...

class DeleteTopicsRequest_v0(Request):
    API_KEY: int = ...
    API_VERSION: int = ...
    RESPONSE_TYPE: Any = ...
    SCHEMA: Any = ...

class DeleteTopicsRequest_v1(Request):
    API_KEY: int = ...
    API_VERSION: int = ...
    RESPONSE_TYPE: Any = ...
    SCHEMA: Any = ...

class DeleteTopicsRequest_v2(Request):
    API_KEY: int = ...
    API_VERSION: int = ...
    RESPONSE_TYPE: Any = ...
    SCHEMA: Any = ...

class DeleteTopicsRequest_v3(Request):
    API_KEY: int = ...
    API_VERSION: int = ...
    RESPONSE_TYPE: Any = ...
    SCHEMA: Any = ...

DeleteTopicsRequest: Any
DeleteTopicsResponse: Any

class ListGroupsResponse_v0(Response):
    API_KEY: int = ...
    API_VERSION: int = ...
    SCHEMA: Any = ...

class ListGroupsResponse_v1(Response):
    API_KEY: int = ...
    API_VERSION: int = ...
    SCHEMA: Any = ...

class ListGroupsResponse_v2(Response):
    API_KEY: int = ...
    API_VERSION: int = ...
    SCHEMA: Any = ...

class ListGroupsRequest_v0(Request):
    API_KEY: int = ...
    API_VERSION: int = ...
    RESPONSE_TYPE: Any = ...
    SCHEMA: Any = ...

class ListGroupsRequest_v1(Request):
    API_KEY: int = ...
    API_VERSION: int = ...
    RESPONSE_TYPE: Any = ...
    SCHEMA: Any = ...

class ListGroupsRequest_v2(Request):
    API_KEY: int = ...
    API_VERSION: int = ...
    RESPONSE_TYPE: Any = ...
    SCHEMA: Any = ...

ListGroupsRequest: Any
ListGroupsResponse: Any

class DescribeGroupsResponse_v0(Response):
    API_KEY: int = ...
    API_VERSION: int = ...
    SCHEMA: Any = ...

class DescribeGroupsResponse_v1(Response):
    API_KEY: int = ...
    API_VERSION: int = ...
    SCHEMA: Any = ...

class DescribeGroupsResponse_v2(Response):
    API_KEY: int = ...
    API_VERSION: int = ...
    SCHEMA: Any = ...

class DescribeGroupsResponse_v3(Response):
    API_KEY: int = ...
    API_VERSION: int = ...
    SCHEMA: Any = ...

class DescribeGroupsRequest_v0(Request):
    API_KEY: int = ...
    API_VERSION: int = ...
    RESPONSE_TYPE: Any = ...
    SCHEMA: Any = ...

class DescribeGroupsRequest_v1(Request):
    API_KEY: int = ...
    API_VERSION: int = ...
    RESPONSE_TYPE: Any = ...
    SCHEMA: Any = ...

class DescribeGroupsRequest_v2(Request):
    API_KEY: int = ...
    API_VERSION: int = ...
    RESPONSE_TYPE: Any = ...
    SCHEMA: Any = ...

class DescribeGroupsRequest_v3(Request):
    API_KEY: int = ...
    API_VERSION: int = ...
    RESPONSE_TYPE: Any = ...
    SCHEMA: Any = ...

DescribeGroupsRequest: Any
DescribeGroupsResponse: Any

class SaslHandShakeResponse_v0(Response):
    API_KEY: int = ...
    API_VERSION: int = ...
    SCHEMA: Any = ...

class SaslHandShakeResponse_v1(Response):
    API_KEY: int = ...
    API_VERSION: int = ...
    SCHEMA: Any = ...

class SaslHandShakeRequest_v0(Request):
    API_KEY: int = ...
    API_VERSION: int = ...
    RESPONSE_TYPE: Any = ...
    SCHEMA: Any = ...

class SaslHandShakeRequest_v1(Request):
    API_KEY: int = ...
    API_VERSION: int = ...
    RESPONSE_TYPE: Any = ...
    SCHEMA: Any = ...

SaslHandShakeRequest: Any
SaslHandShakeResponse: Any

class DescribeAclsResponse_v0(Response):
    API_KEY: int = ...
    API_VERSION: int = ...
    SCHEMA: Any = ...

class DescribeAclsResponse_v1(Response):
    API_KEY: int = ...
    API_VERSION: int = ...
    SCHEMA: Any = ...

class DescribeAclsRequest_v0(Request):
    API_KEY: int = ...
    API_VERSION: int = ...
    RESPONSE_TYPE: Any = ...
    SCHEMA: Any = ...

class DescribeAclsRequest_v1(Request):
    API_KEY: int = ...
    API_VERSION: int = ...
    RESPONSE_TYPE: Any = ...
    SCHEMA: Any = ...

DescribeAclsRequest: Any
DescribeAclsResponse: Any

class CreateAclsResponse_v0(Response):
    API_KEY: int = ...
    API_VERSION: int = ...
    SCHEMA: Any = ...

class CreateAclsResponse_v1(Response):
    API_KEY: int = ...
    API_VERSION: int = ...
    SCHEMA: Any = ...

class CreateAclsRequest_v0(Request):
    API_KEY: int = ...
    API_VERSION: int = ...
    RESPONSE_TYPE: Any = ...
    SCHEMA: Any = ...

class CreateAclsRequest_v1(Request):
    API_KEY: int = ...
    API_VERSION: int = ...
    RESPONSE_TYPE: Any = ...
    SCHEMA: Any = ...

CreateAclsRequest: Any
CreateAclsResponse: Any

class DeleteAclsResponse_v0(Response):
    API_KEY: int = ...
    API_VERSION: int = ...
    SCHEMA: Any = ...

class DeleteAclsResponse_v1(Response):
    API_KEY: int = ...
    API_VERSION: int = ...
    SCHEMA: Any = ...

class DeleteAclsRequest_v0(Request):
    API_KEY: int = ...
    API_VERSION: int = ...
    RESPONSE_TYPE: Any = ...
    SCHEMA: Any = ...

class DeleteAclsRequest_v1(Request):
    API_KEY: int = ...
    API_VERSION: int = ...
    RESPONSE_TYPE: Any = ...
    SCHEMA: Any = ...

DeleteAclsRequest: Any
DeleteAclsResponse: Any

class AlterConfigsResponse_v0(Response):
    API_KEY: int = ...
    API_VERSION: int = ...
    SCHEMA: Any = ...

class AlterConfigsResponse_v1(Response):
    API_KEY: int = ...
    API_VERSION: int = ...
    SCHEMA: Any = ...

class AlterConfigsRequest_v0(Request):
    API_KEY: int = ...
    API_VERSION: int = ...
    RESPONSE_TYPE: Any = ...
    SCHEMA: Any = ...

class AlterConfigsRequest_v1(Request):
    API_KEY: int = ...
    API_VERSION: int = ...
    RESPONSE_TYPE: Any = ...
    SCHEMA: Any = ...

AlterConfigsRequest: Any
AlterConfigsResponse: Any

class DescribeConfigsResponse_v0(Response):
    API_KEY: int = ...
    API_VERSION: int = ...
    SCHEMA: Any = ...

class DescribeConfigsResponse_v1(Response):
    API_KEY: int = ...
    API_VERSION: int = ...
    SCHEMA: Any = ...

class DescribeConfigsResponse_v2(Response):
    API_KEY: int = ...
    API_VERSION: int = ...
    SCHEMA: Any = ...

class DescribeConfigsRequest_v0(Request):
    API_KEY: int = ...
    API_VERSION: int = ...
    RESPONSE_TYPE: Any = ...
    SCHEMA: Any = ...

class DescribeConfigsRequest_v1(Request):
    API_KEY: int = ...
    API_VERSION: int = ...
    RESPONSE_TYPE: Any = ...
    SCHEMA: Any = ...

class DescribeConfigsRequest_v2(Request):
    API_KEY: int = ...
    API_VERSION: int = ...
    RESPONSE_TYPE: Any = ...
    SCHEMA: Any = ...

DescribeConfigsRequest: Any
DescribeConfigsResponse: Any

class SaslAuthenticateResponse_v0(Response):
    API_KEY: int = ...
    API_VERSION: int = ...
    SCHEMA: Any = ...

class SaslAuthenticateResponse_v1(Response):
    API_KEY: int = ...
    API_VERSION: int = ...
    SCHEMA: Any = ...

class SaslAuthenticateRequest_v0(Request):
    API_KEY: int = ...
    API_VERSION: int = ...
    RESPONSE_TYPE: Any = ...
    SCHEMA: Any = ...

class SaslAuthenticateRequest_v1(Request):
    API_KEY: int = ...
    API_VERSION: int = ...
    RESPONSE_TYPE: Any = ...
    SCHEMA: Any = ...

SaslAuthenticateRequest: Any
SaslAuthenticateResponse: Any

class CreatePartitionsResponse_v0(Response):
    API_KEY: int = ...
    API_VERSION: int = ...
    SCHEMA: Any = ...

class CreatePartitionsResponse_v1(Response):
    API_KEY: int = ...
    API_VERSION: int = ...
    SCHEMA: Any = ...

class CreatePartitionsRequest_v0(Request):
    API_KEY: int = ...
    API_VERSION: int = ...
    RESPONSE_TYPE: Any = ...
    SCHEMA: Any = ...

class CreatePartitionsRequest_v1(Request):
    API_KEY: int = ...
    API_VERSION: int = ...
    SCHEMA: Any = ...
    RESPONSE_TYPE: Any = ...

CreatePartitionsRequest: Any
CreatePartitionsResponse: Any
