from kafka.protocol.api import Request as Request, Response as Response
from kafka.protocol.types import Array as Array, Int16 as Int16, Int32 as Int32, Int64 as Int64, Int8 as Int8, Schema as Schema, String as String
from typing import Any

class OffsetCommitResponse_v0(Response):
    API_KEY: int = ...
    API_VERSION: int = ...
    SCHEMA: Any = ...

class OffsetCommitResponse_v1(Response):
    API_KEY: int = ...
    API_VERSION: int = ...
    SCHEMA: Any = ...

class OffsetCommitResponse_v2(Response):
    API_KEY: int = ...
    API_VERSION: int = ...
    SCHEMA: Any = ...

class OffsetCommitResponse_v3(Response):
    API_KEY: int = ...
    API_VERSION: int = ...
    SCHEMA: Any = ...

class OffsetCommitRequest_v0(Request):
    API_KEY: int = ...
    API_VERSION: int = ...
    RESPONSE_TYPE: Any = ...
    SCHEMA: Any = ...

class OffsetCommitRequest_v1(Request):
    API_KEY: int = ...
    API_VERSION: int = ...
    RESPONSE_TYPE: Any = ...
    SCHEMA: Any = ...

class OffsetCommitRequest_v2(Request):
    API_KEY: int = ...
    API_VERSION: int = ...
    RESPONSE_TYPE: Any = ...
    SCHEMA: Any = ...
    DEFAULT_GENERATION_ID: int = ...
    DEFAULT_RETENTION_TIME: int = ...

class OffsetCommitRequest_v3(Request):
    API_KEY: int = ...
    API_VERSION: int = ...
    RESPONSE_TYPE: Any = ...
    SCHEMA: Any = ...

OffsetCommitRequest: Any
OffsetCommitResponse: Any

class OffsetFetchResponse_v0(Response):
    API_KEY: int = ...
    API_VERSION: int = ...
    SCHEMA: Any = ...

class OffsetFetchResponse_v1(Response):
    API_KEY: int = ...
    API_VERSION: int = ...
    SCHEMA: Any = ...

class OffsetFetchResponse_v2(Response):
    API_KEY: int = ...
    API_VERSION: int = ...
    SCHEMA: Any = ...

class OffsetFetchResponse_v3(Response):
    API_KEY: int = ...
    API_VERSION: int = ...
    SCHEMA: Any = ...

class OffsetFetchRequest_v0(Request):
    API_KEY: int = ...
    API_VERSION: int = ...
    RESPONSE_TYPE: Any = ...
    SCHEMA: Any = ...

class OffsetFetchRequest_v1(Request):
    API_KEY: int = ...
    API_VERSION: int = ...
    RESPONSE_TYPE: Any = ...
    SCHEMA: Any = ...

class OffsetFetchRequest_v2(Request):
    API_KEY: int = ...
    API_VERSION: int = ...
    RESPONSE_TYPE: Any = ...
    SCHEMA: Any = ...

class OffsetFetchRequest_v3(Request):
    API_KEY: int = ...
    API_VERSION: int = ...
    RESPONSE_TYPE: Any = ...
    SCHEMA: Any = ...

OffsetFetchRequest: Any
OffsetFetchResponse: Any

class GroupCoordinatorResponse_v0(Response):
    API_KEY: int = ...
    API_VERSION: int = ...
    SCHEMA: Any = ...

class GroupCoordinatorResponse_v1(Response):
    API_KEY: int = ...
    API_VERSION: int = ...
    SCHEMA: Any = ...

class GroupCoordinatorRequest_v0(Request):
    API_KEY: int = ...
    API_VERSION: int = ...
    RESPONSE_TYPE: Any = ...
    SCHEMA: Any = ...

class GroupCoordinatorRequest_v1(Request):
    API_KEY: int = ...
    API_VERSION: int = ...
    RESPONSE_TYPE: Any = ...
    SCHEMA: Any = ...

GroupCoordinatorRequest: Any
GroupCoordinatorResponse: Any
