from kafka.protocol.api import Request as Request, Response as Response
from kafka.protocol.types import Array as Array, Bytes as Bytes, Int16 as Int16, Int32 as Int32, Int64 as Int64, Int8 as Int8, Schema as Schema, String as String
from typing import Any

class FetchResponse_v0(Response):
    API_KEY: int = ...
    API_VERSION: int = ...
    SCHEMA: Any = ...

class FetchResponse_v1(Response):
    API_KEY: int = ...
    API_VERSION: int = ...
    SCHEMA: Any = ...

class FetchResponse_v2(Response):
    API_KEY: int = ...
    API_VERSION: int = ...
    SCHEMA: Any = ...

class FetchResponse_v3(Response):
    API_KEY: int = ...
    API_VERSION: int = ...
    SCHEMA: Any = ...

class FetchResponse_v4(Response):
    API_KEY: int = ...
    API_VERSION: int = ...
    SCHEMA: Any = ...

class FetchResponse_v5(Response):
    API_KEY: int = ...
    API_VERSION: int = ...
    SCHEMA: Any = ...

class FetchResponse_v6(Response):
    API_KEY: int = ...
    API_VERSION: int = ...
    SCHEMA: Any = ...

class FetchRequest_v0(Request):
    API_KEY: int = ...
    API_VERSION: int = ...
    RESPONSE_TYPE: Any = ...
    SCHEMA: Any = ...

class FetchRequest_v1(Request):
    API_KEY: int = ...
    API_VERSION: int = ...
    RESPONSE_TYPE: Any = ...
    SCHEMA: Any = ...

class FetchRequest_v2(Request):
    API_KEY: int = ...
    API_VERSION: int = ...
    RESPONSE_TYPE: Any = ...
    SCHEMA: Any = ...

class FetchRequest_v3(Request):
    API_KEY: int = ...
    API_VERSION: int = ...
    RESPONSE_TYPE: Any = ...
    SCHEMA: Any = ...

class FetchRequest_v4(Request):
    API_KEY: int = ...
    API_VERSION: int = ...
    RESPONSE_TYPE: Any = ...
    SCHEMA: Any = ...

class FetchRequest_v5(Request):
    API_KEY: int = ...
    API_VERSION: int = ...
    RESPONSE_TYPE: Any = ...
    SCHEMA: Any = ...

class FetchRequest_v6(Request):
    API_KEY: int = ...
    API_VERSION: int = ...
    RESPONSE_TYPE: Any = ...
    SCHEMA: Any = ...

FetchRequest: Any
FetchResponse: Any
