from typing import Any, Optional

class KafkaBytes(bytearray):
    def __init__(self, size: Any) -> None: ...
    def read(self, nbytes: Optional[Any] = ...): ...
    def write(self, data: Any) -> None: ...
    def seek(self, idx: Any) -> None: ...
    def tell(self): ...
