from kafka.protocol.api import Request as Request, Response as Response
from kafka.protocol.struct import Struct as Struct
from kafka.protocol.types import Array as Array, Bytes as Bytes, Int16 as Int16, Int32 as Int32, Schema as Schema, String as String
from typing import Any

class JoinGroupResponse_v0(Response):
    API_KEY: int = ...
    API_VERSION: int = ...
    SCHEMA: Any = ...

class JoinGroupResponse_v1(Response):
    API_KEY: int = ...
    API_VERSION: int = ...
    SCHEMA: Any = ...

class JoinGroupResponse_v2(Response):
    API_KEY: int = ...
    API_VERSION: int = ...
    SCHEMA: Any = ...

class JoinGroupRequest_v0(Request):
    API_KEY: int = ...
    API_VERSION: int = ...
    RESPONSE_TYPE: Any = ...
    SCHEMA: Any = ...
    UNKNOWN_MEMBER_ID: str = ...

class JoinGroupRequest_v1(Request):
    API_KEY: int = ...
    API_VERSION: int = ...
    RESPONSE_TYPE: Any = ...
    SCHEMA: Any = ...
    UNKNOWN_MEMBER_ID: str = ...

class JoinGroupRequest_v2(Request):
    API_KEY: int = ...
    API_VERSION: int = ...
    RESPONSE_TYPE: Any = ...
    SCHEMA: Any = ...
    UNKNOWN_MEMBER_ID: str = ...

JoinGroupRequest: Any
JoinGroupResponse: Any

class ProtocolMetadata(Struct):
    SCHEMA: Any = ...

class SyncGroupResponse_v0(Response):
    API_KEY: int = ...
    API_VERSION: int = ...
    SCHEMA: Any = ...

class SyncGroupResponse_v1(Response):
    API_KEY: int = ...
    API_VERSION: int = ...
    SCHEMA: Any = ...

class SyncGroupRequest_v0(Request):
    API_KEY: int = ...
    API_VERSION: int = ...
    RESPONSE_TYPE: Any = ...
    SCHEMA: Any = ...

class SyncGroupRequest_v1(Request):
    API_KEY: int = ...
    API_VERSION: int = ...
    RESPONSE_TYPE: Any = ...
    SCHEMA: Any = ...

SyncGroupRequest: Any
SyncGroupResponse: Any

class MemberAssignment(Struct):
    SCHEMA: Any = ...

class HeartbeatResponse_v0(Response):
    API_KEY: int = ...
    API_VERSION: int = ...
    SCHEMA: Any = ...

class HeartbeatResponse_v1(Response):
    API_KEY: int = ...
    API_VERSION: int = ...
    SCHEMA: Any = ...

class HeartbeatRequest_v0(Request):
    API_KEY: int = ...
    API_VERSION: int = ...
    RESPONSE_TYPE: Any = ...
    SCHEMA: Any = ...

class HeartbeatRequest_v1(Request):
    API_KEY: int = ...
    API_VERSION: int = ...
    RESPONSE_TYPE: Any = ...
    SCHEMA: Any = ...

HeartbeatRequest: Any
HeartbeatResponse: Any

class LeaveGroupResponse_v0(Response):
    API_KEY: int = ...
    API_VERSION: int = ...
    SCHEMA: Any = ...

class LeaveGroupResponse_v1(Response):
    API_KEY: int = ...
    API_VERSION: int = ...
    SCHEMA: Any = ...

class LeaveGroupRequest_v0(Request):
    API_KEY: int = ...
    API_VERSION: int = ...
    RESPONSE_TYPE: Any = ...
    SCHEMA: Any = ...

class LeaveGroupRequest_v1(Request):
    API_KEY: int = ...
    API_VERSION: int = ...
    RESPONSE_TYPE: Any = ...
    SCHEMA: Any = ...

LeaveGroupRequest: Any
LeaveGroupResponse: Any
