from kafka.protocol.api import Request as Request, Response as Response
from kafka.protocol.types import Array as Array, Int16 as Int16, Int32 as Int32, Int64 as Int64, Int8 as Int8, Schema as Schema, String as String
from typing import Any

UNKNOWN_OFFSET: int

class OffsetResetStrategy:
    LATEST: int = ...
    EARLIEST: int = ...
    NONE: int = ...

class OffsetResponse_v0(Response):
    API_KEY: int = ...
    API_VERSION: int = ...
    SCHEMA: Any = ...

class OffsetResponse_v1(Response):
    API_KEY: int = ...
    API_VERSION: int = ...
    SCHEMA: Any = ...

class OffsetResponse_v2(Response):
    API_KEY: int = ...
    API_VERSION: int = ...
    SCHEMA: Any = ...

class OffsetRequest_v0(Request):
    API_KEY: int = ...
    API_VERSION: int = ...
    RESPONSE_TYPE: Any = ...
    SCHEMA: Any = ...
    DEFAULTS: Any = ...

class OffsetRequest_v1(Request):
    API_KEY: int = ...
    API_VERSION: int = ...
    RESPONSE_TYPE: Any = ...
    SCHEMA: Any = ...
    DEFAULTS: Any = ...

class OffsetRequest_v2(Request):
    API_KEY: int = ...
    API_VERSION: int = ...
    RESPONSE_TYPE: Any = ...
    SCHEMA: Any = ...
    DEFAULTS: Any = ...

OffsetRequest: Any
OffsetResponse: Any
