from kafka.protocol.abstract import AbstractType as AbstractType
from typing import Any

class Struct(AbstractType):
    SCHEMA: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    @classmethod
    def encode(cls, item: Any): ...
    @classmethod
    def decode(cls, data: Any): ...
    def get_item(self, name: Any): ...
    def __hash__(self) -> Any: ...
    def __eq__(self, other: Any) -> Any: ...
