image_name: "aiolibs/kafka"
versions:
  -
    kafka: "0.9.0.1"
    scala: "2.11"
  -
    kafka: "0.10.0.0"
    scala: "2.11"
  -
    kafka: "0.10.0.1"
    scala: "2.11"
  -
    kafka: "0.10.1.0"
    scala: "2.11"
  -
    kafka: "0.10.1.1"
    scala: "2.11"
  -
    kafka: "0.10.2.1"
    scala: "2.11"
  -
    kafka: "0.11.0.0"
    scala: "2.12"