image_name: "aiolibs/kafka"
versions:
  -
    kafka: "0.9.0.1"
    scala: "2.11"
  -
    kafka: "0.10.2.1"
    scala: "2.11"
  -
    kafka: "0.11.0.3"
    scala: "2.12"
  -
    kafka: "1.1.1"
    scala: "2.12"
  -
    kafka: "2.1.1"
    scala: "2.12"
  -
    kafka: "2.2.2"
    scala: "2.12"
  -
    kafka: "2.3.1"
    scala: "2.12"
  -
    kafka: "2.4.0"
    scala: "2.12"
