"""
This type stub file was generated by pyright.
"""

from .abc import ConsumerRebalanceListener
from .consumer import AIOKafkaConsumer
from .errors import ConsumerStoppedError, IllegalOperation
from .structs import ConsumerRecord, OffsetAndMetadata, OffsetAndTimestamp, TopicPartition

__version__ = ...
__all__ = ["AIOKafkaConsumer", "ConsumerRebalanceListener", "ConsumerStoppedError", "IllegalOperation", "ConsumerRecord", "TopicPartition", "OffsetAndTimestamp", "OffsetAndMetadata"]
