from .default_records import DefaultRecordBatch
from .legacy_records import LegacyRecordBatch

class MemoryRecords:
    def __init__(self, bytes_data: bytes) -> None: ...
    def size_in_bytes(self) -> int: ...
    def has_next(self) -> bool: ...
    def next_batch(self) -> DefaultRecordBatch | LegacyRecordBatch | None: ...
