from typing import Any

class Histogram:
    def __init__(self, bin_scheme: Any) -> None: ...
    def record(self, value: Any) -> None: ...
    def value(self, quantile: Any): ...
    @property
    def counts(self): ...
    def clear(self) -> None: ...
    class ConstantBinScheme:
        def __init__(self, bins: Any, min_val: Any, max_val: Any) -> None: ...
        @property
        def bins(self): ...
        def from_bin(self, b: Any): ...
        def to_bin(self, x: Any): ...
    class LinearBinScheme:
        def __init__(self, num_bins: Any, max_val: Any) -> None: ...
        @property
        def bins(self): ...
        def from_bin(self, b: Any): ...
        def to_bin(self, x: Any): ...
