from kafka.errors import QuotaViolationError as QuotaViolationError
from kafka.metrics import KafkaMetric as KafkaMetric
from typing import Any, Optional

class Sensor:
    def __init__(self, registry: Any, name: Any, parents: Any, config: Any, inactive_sensor_expiration_time_seconds: Any) -> None: ...
    @property
    def name(self): ...
    @property
    def metrics(self): ...
    def record(self, value: float = ..., time_ms: Optional[Any] = ...) -> None: ...
    def add_compound(self, compound_stat: Any, config: Optional[Any] = ...) -> None: ...
    def add(self, metric_name: Any, stat: Any, config: Optional[Any] = ...) -> None: ...
    def has_expired(self): ...
