from kafka.metrics.measurable_stat import AbstractMeasurableStat as AbstractMeasurableStat
from typing import Any

class Total(AbstractMeasurableStat):
    def __init__(self, value: float = ...) -> None: ...
    def record(self, config: Any, value: Any, now: Any) -> None: ...
    def measure(self, config: Any, now: Any): ...
