from kafka.protocol.struct import Struct as Struct
from kafka.protocol.types import Array as Array, Bytes as Bytes, Int16 as Int16, Int32 as Int32, Schema as Schema, String as String
from kafka.structs import TopicPartition as TopicPartition
from typing import Any

class ConsumerProtocolMemberMetadata(Struct):
    SCHEMA: Any = ...

class ConsumerProtocolMemberAssignment(Struct):
    SCHEMA: Any = ...
    def partitions(self): ...

class ConsumerProtocol:
    PROTOCOL_TYPE: str = ...
    ASSIGNMENT_STRATEGIES: Any = ...
    METADATA: Any = ...
    ASSIGNMENT: Any = ...
